Repository Nadi0128/ToDo-list-application-LALEYE-Nadirath-CDOF2, pull requests merged in 2025-01, with the labels that each got.

#10 Update README.md
  README.md
Labels: documentation

#9 fix bug empty input
  index.js
Labels: bug

#11 improve project
  index.js
Labels: enhancement

#21 Improve project
  README.md
  index.js
Labels: enhancement
